use_frameworks!

platform :ios, '10.0'

target 'QXWebView_Example' do
  pod 'QXWebView', :path => '../'

  target 'QXWebView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
